name: sport
description: A new Flutter project.
publish_to: 'none'
version: 2.2.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  awesome_notifications: ^0.7.4+1
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  image_picker: ^1.0.1
  intl: ^0.18.0
  package_info_plus: ^4.0.1
  reactive_forms: ^16.0.2
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.2
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  table_calendar: ^3.0.9
  share_plus: ^7.0.2
  flutter_markdown: ^0.6.17
  webview_flutter: ^4.2.2
  photo_view: ^0.14.0
  swipe_image_gallery: ^0.8.3
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  pdf: ^3.10.4
dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/audios/
    - assets/fonts/
    - assets/images/
    - assets/jsons/
    - assets/translations/
